import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProviderWrapper } from "./providers/SessionProviderWrapper"; 
import Link from "next/link";
import FooterNav from "./components/FooterNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moodify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          {children}
          <FooterNav />
          <footer className="text-sm text-gray-400 text-center py-6 pb-20">
            <p>
              <Link href="/privacy" className="underline">Privacyverklaring</Link> •{' '}
              <Link href="/terms" className="underline">Gebruiksvoorwaarden</Link>
            </p>
          </footer>
        </SessionProviderWrapper>
      </body>
  </html>  
  );
}
