import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProviderWrapper } from "./providers/SessionProviderWrapper";
import Link from "next/link";
import FooterNav from "./components/FooterNav";
import { InformationCircleIcon } from "@heroicons/react/24/outline";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moodify",
  description: "Generated by Moodify",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProviderWrapper>
          {children}
          <FooterNav />
          <footer className="text-sm text-gray-400 text-center py-6 pb-20">
            <p>
              <Link href="/privacy" className="underline">Privacyverklaring</Link> •{' '}
              <Link href="/terms" className="underline">Gebruiksvoorwaarden</Link>
            </p>
            <p className="mt-2 text-xs text-zinc-500 flex items-center justify-center gap-1">
              <InformationCircleIcon className="h-4 w-4" aria-hidden="true" />
              <span>
                Spotify Developer Terms (v10) - korte samenvatting.{' '}
                <Link
                  href="https://developer.spotify.com/terms"
                  target="_blank"
                  rel="noreferrer"
                  className="underline text-emerald-300"
                >
                  Bekijk volledige voorwaarden
                </Link>
              </span>
            </p>
          </footer>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
