export const countries: Record<string, string> = {
    NL: 'Nederland',
    BE: 'België',
    US: 'Verenigde Staten',
    GB: 'Verenigd Koninkrijk',
    DE: 'Duitsland',
    FR: 'Frankrijk',
    ES: 'Spanje',
    IT: 'Italië',
    JP: 'Japan',
    AU: 'Australië',
    CA: 'Canada',
    BR: 'Brazilië',
    SE: 'Zweden',
    NO: 'Noorwegen',
    DK: 'Denemarken',
    FI: 'Finland',
    PL: 'Polen',
    TR: 'Turkije',
    MX: 'Mexico',
    IN: 'India',
    ID: 'Indonesië',
    PH: 'Filipijnen',
    AR: 'Argentinië',
    ZA: 'Zuid-Afrika',
    KR: 'Zuid-Korea',
}
